# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "puppetmaster" do |puppetmaster|
    puppetmaster.vm.box = "ubuntu/bionic64"
    puppetmaster.vm.network "private_network", ip: "192.168.33.10"
  end
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.network "private_network", ip: "192.168.33.11"
  end
end
