{
 "title": "Decentralized Blackbox Exporter",
 "description": "Dashboard for decentralized Blackbox Exporters. Mostly for DNS and HTTP/HTTPS Tests",
 "tags": [
  "prometheus",
  "blackbox"
 ],
 "time": { "from": "2019-01-31T15:30:59.657Z", "to": "2019-01-31T15:32:24.639Z" },
 "templating": {
  "list": [
   {
    "name": "blackboxes",
    "label": "blackboxes",
    "query": "label_values(up,blackbox_instance)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{blackbox_instance=~\"$blackboxes\"},instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Status Code",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average HTTP/HTTPS Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$targets\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$targets\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Transfer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"transfer\",blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Connect",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\",blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Processing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"processing\",blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Resolve",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"resolve\",blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "HTTPS TLS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"tls\",blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{instance}}]"
    }
   ]
  }
 ]
}